name: Publish Release

on:
    push:
        tags:
            - '*'

permissions:
    contents: write

jobs:
    release-pro:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Create ultimate-post-kit directory and move files
              run: |
                  mkdir -p ultimate-post-kit &&
                  find . -maxdepth 1 -not -name 'ultimate-post-kit' -exec mv {} ultimate-post-kit \;

            - name: Archive release
              uses: thedoctor0/zip-release@0.7.6
              with:
                  filename: 'ultimate-post-kit.zip'
                  exclusions: "/*node_modules/* /*src/* /*scss/* /*gruntfile.js /*package.json /*package-lock.json /*sync.ffs_db /*.idea/* /*.DS_Store /*.gitignore /*.github/* /*.git/* /*LICENSE /*.eslintrc /*.gitattributes /*.prettierrc"
            - name: Display release
              run: ls -a

            - name: Build Change Log
              id: changelog
              uses: dorny/paths-filter@v2
              with:
                  filters: |
                      changelog.txt

            - name: Create Release
              uses: ncipollo/release-action@v1.14.0
              with:
                  artifacts: './ultimate-post-kit.zip'
                  token: ${{ secrets.TOKEN }}
                  removeArtifacts: true
                  allowUpdates: true
                  makeLatest: true
                  tag: ${{ github.ref_name }}
